### PR TITLE
update demo.py

### PR DESCRIPTION
**Pull request by riggy2013**

### CODE REVIEW

**Comment by riggy2013** [comment]
The fix is verified. It is good now.
This PR is to update previous wrongly merged test code. Now the new test string is appended at last.

**Comment by eroux** [comment]
thanks, I'd prefer avoiding having files specific to editors though, can you remove the launch.json file please? (you can add it to `.gitignore` if you want, I don't mind)

**Comment by riggy2013** [comment]
I am an IT engineer interested in Tibetan. Try to find some fun stuff w/ both Tibetan related and coding. I am thinking of making a wylie converter and found your git. 

I used slad2019 account before but it created some mess here. Sorry for that.

**Comment by eroux** [comment]
thanks! Interesting, don't hesitate to get involved in any project in this github org, any help is welcome!

**Pull request merged**
