### PR TITLE
minor bugs.

### PR DESCRIPTION
**Pull request by riggy2013**

### CODE REVIEW

**Comment by riggy2013** [comment]
minor bugs, syntax error w/ new demo.py
consonantString => self.consonantString
consonants.add => consonants.append

**Comment by eroux** [comment]
thanks a lot!

**Comment by eroux** [comment]
the warning printed in the demo now contain some weird data, ex:

```
'line 1: "snga": Superscript "s" does not occur above combination "".
```

the final string of the warning shouldn't be empty (it should be `"nga"`)... I'll try to take a look this week-end (if you don't have time before)

**Comment by riggy2013** [comment]
Elie,

I am checking it too.

The input is correct.

snga 'phros or སྣྔྔ་འཕྲྲོས་ means temporarily.

The error seems in check_strict. What do you want to get from check_strict?

if t2 != None and self.isSuperscript(t) and self.superscript(t, t2):
if self.check_strict:
next = self.consonantString(tokens, i + 1)
if not self.superscript(t, next):
next = next.replace("+", "")
warns.append("Superscript \"" + t + "\" does not occur above combination \""
+ next + "\".")

if I understand correctly, you want to add next consonant and try to check
superscript like ""k+y","g+y","m+y","b+w","ts+w","g+w"". Two issues here:
1. if next consonantString is empty, you should ignore the check. This is
what happening w/ "snag".
2. if there is indeed next consonantString, it seems you should append it
to t2 and do check.

Thanks,

David Peng

**Comment by eroux** [comment]
ok, I think I've fixed the problem... can you give it a try? BTW, thanks a lot for your help! People interested in Tibetan are rare, may I ask you on what kind of projects you will be using pyewts?

**Pull request merged**
